name: web3_provider_with_contract_call_example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  web3:
    path: ../

  cupertino_icons: ^1.0.2

  get:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true